import { Suspense, useMemo } from "react";
import { useDocumentContext } from "../contexts";
import { ErrorBoundary } from "../components/ErrorBoundary";
import type {
  PluginSlotComponent,
  PluginSlotContextMap,
  SupplementarySlotName,
  TabSlotName,
} from "./types";
import { createPluginSlotRegistry } from "./registry";
import type { PluginSlotRegistry } from "./registry";

/** Isolates one plugin's render in its own error boundary + Suspense
 * boundary, tagged with `label` for the console error, so one broken or
 * slow-loading plugin can't take down the document or a sibling plugin.
 * Shared by `PluginSlot` (one boundary per component in a slot) and the
 * `*.operation.tab` containers (one boundary around whichever tab is active). */
export function PluginBoundary({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <ErrorBoundary
      fallback={null}
      onError={(error) => console.error(`[apiuikit] plugin error in slot "${label}":`, error)}
    >
      <Suspense fallback={null}>{children}</Suspense>
    </ErrorBoundary>
  );
}

/** Every plugin (from `useDocumentContext().plugins`) that fills `name`, in
 * registration order. */
function usePluginSlotRegistry(): PluginSlotRegistry {
  const { plugins, pluginSlotRegistry } = useDocumentContext();
  // The fallback supports consumers that manually construct DocumentContext
  // values. Library providers always supply the precomputed registry.
  return useMemo(
    () => pluginSlotRegistry ?? createPluginSlotRegistry(plugins ?? []),
    [pluginSlotRegistry, plugins],
  );
}

export interface PluginSlotEntry<N extends SupplementarySlotName> {
  id: string;
  pluginName: string;
  Component: PluginSlotComponent<N>;
}

export function usePluginSlot<N extends SupplementarySlotName>(name: N): readonly PluginSlotEntry<N>[] {
  const registry = usePluginSlotRegistry();
  return (registry.get(name) ?? []) as readonly PluginSlotEntry<N>[];
}

export interface PluginSlotProps<N extends SupplementarySlotName> {
  name: N;
  context: PluginSlotContextMap[N];
}

/**
 * Renders every plugin registered for `name`, each isolated in its own
 * `ErrorBoundary` + `Suspense` boundary so one broken or slow-loading plugin
 * can't take down the document or its sibling plugins. Renders nothing when
 * no plugin fills this slot.
 */
export function PluginSlot<N extends SupplementarySlotName>({ name, context }: PluginSlotProps<N>) {
  const entries = usePluginSlot(name);
  if (entries.length === 0) return null;

  return (
    <>
      {entries.map(({ id, pluginName, Component }) => (
        <PluginBoundary key={id} label={`${name}:${pluginName} (${id})`}>
          <Component {...context} />
        </PluginBoundary>
      ))}
    </>
  );
}

/** One plugin's fill of a `*.operation.tab` slot, resolved into what the
 * operation panel's tab strip needs. `id` is generated by the registry and
 * does not depend on the plugin's user-facing name. */
export interface PluginTabEntry<N extends TabSlotName> {
  id: string;
  pluginName: string;
  label: string;
  Component: PluginSlotComponent<N>;
}

/** Every plugin filling the `*.operation.tab` slot `name`, in registration
 * order — what `PathOperation`/`Operation` build their tab strip from. Not
 * meant for plugin authors themselves (a plugin doesn't render its own tab
 * strip); exported alongside `PluginSlot`/`usePluginSlot` for the same reason
 * those are: only relevant if you're building something that itself hosts
 * `*.operation.tab` plugins, like a custom operation panel. */
export function useOperationTabPlugins<N extends TabSlotName>(name: N): readonly PluginTabEntry<N>[] {
  const registry = usePluginSlotRegistry();
  return (registry.get(name) ?? []) as readonly PluginTabEntry<N>[];
}

export default PluginSlot;
